server:
  port: 8081

app:
  log-path: logs

logging:
  level:
    org.example.logs.RequestLoggingFilter: INFO

spring:
  datasource:
    url: jdbc:postgresql://localhost:1011/auth_db
    username: auth_user
    password: 123 # It will eventually be moved to .env

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml

jwt:
  secret: superDlugiKluczMinimum32ZnakiTutaj

management:
  endpoints:
    web:
      exposure:
        include: '*'

  endpoint:
    health:
      show-details: always

kafka:
  topics:
    mail-registration: mail.registration.user
  poll-interval-ms: 5000

mail:
  user-registration:
    subject: Welcome in Cinema Service!
    template: user_registration_v1
