version: '3.8'
services:
  db:
    container_name: cinema
    image: postgres:16
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: cinema
      POSTGRES_PASSWORD: 123 # It will eventually be moved to .env
    ports:
      - "1010:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d