server:
  port: 8082

app:
  log-path: logs

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: mail-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  mail:
    sender: no-reply@cinema-service.com
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: ${MAILTRAP_USERNAME}
    password: ${MAILTRAP_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

kafka:
  topics:
    mail-registration: mail.registration.user
    mail-registration-dlq: mail.registration.user.dlq

management:
  endpoints:
    web:
      exposure:
        include: '*'

  endpoint:
    health:
      show-details: always