server:
  port: 8080

app:
  log-path: ./cinema-service/logs

logging:
  level:
    org.example.logs.RequestLoggingFilter: INFO

spring:
  datasource:
    url: jdbc:postgresql://localhost:1010/cinema_db
    username: cinema_user
    password: 123 # It will eventually be moved to .env

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml

jwt:
  secret: superDlugiKluczMinimum32ZnakiTutaj
