scrape_configs:
  - job_name: 'Auth Service Metrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    basic_auth:
      username: 'prometheus'
      password: '123'
    static_configs:
      - targets: ['host.docker.internal:8081']
        labels:
          application: 'Auth Service'

  - job_name: 'Cinema Service Metrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    basic_auth:
      username: 'prometheus'
      password: '123'
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]
        labels:
          application: 'Cinema Service'